In [40]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import os
import pandas as pd
import numpy as np
import geopy.distance

In [19]:
# 성동구 데이터 불러오기
df1 = pd.read_csv("C:/Users/gherwt/KDT30/p1/dong.csv", encoding = "cp949")
df2 = pd.read_csv("C:/Users/gherwt/KDT30/p1/school_location.csv", encoding = "cp949")

In [20]:
# 위도 경도 이름 변경
df1 = df1.rename(columns={'위도':'dong_lat'})
df1 = df1.rename(columns={'경도':'dong_long'})

In [21]:
# 위도 경도 이름 변경
df2 = df2.rename(columns={'위도':'school_lat'})
df2 = df2.rename(columns={'경도':'school_long'})

In [22]:
# 법정동을 기준으로 병합해준다.
data = df2.merge(df1 , on = '법정동' , how = 'left') # 데이터 합치기
data.head(2)

,학교명,주소,법정동,school_lat,school_long,dong_lat,dong_long
0,서울숭신초등학교,서울특별시 성동구 마장로 161,하왕십리동,37.566756,127.030334,37.562462,127.029586
1,행당중학교,서울특별시 성동구 왕십리로 189,행당동,37.561700,127.034703,37.559076,127.035869

In [41]:
# zip 함수로 위경도 묶어주기
data['dong_coord'] = pd.Series(zip(data['dong_lat'], data['dong_long']))
data['school_coord'] = pd.Series(zip(data['school_lat'], data['school_long']))
data.head(2)

,학교명,주소,법정동,school_lat,school_long,dong_lat,dong_long,dong_coord,shcool_coord,school_coord,distance
0,서울숭신초등학교,서울특별시 성동구 마장로 161,하왕십리동,37.566756,127.030334,37.562462,127.029586,"(37.562462, 127.029586)","(37.5667563, 127.0303341)","(37.5667563, 127.0303341)",0.481178
1,행당중학교,서울특별시 성동구 왕십리로 189,행당동,37.561700,127.034703,37.559076,127.035869,"(37.559076, 127.035869)","(37.5617004, 127.0347032)","(37.5617004, 127.0347032)",0.308953

In [26]:
# 위, 경도 값의 차를 이용해서 거리를 구해준다.
data['distance'] = data.apply(lambda x : geopy.distance.distance(x['dong_coord'] , x['school_coord']).km , axis =1 ) # 거리계산

In [30]:
data.head(2)

,학교명,주소,법정동,school_lat,school_long,dong_lat,dong_long,dong_coord,shcool_coord,school_coord,distance
0,서울숭신초등학교,서울특별시 성동구 마장로 161,하왕십리동,37.566756,127.030334,37.562462,127.029586,"(37.562462, 127.029586)","(37.5667563, 127.0303341)","(37.5667563, 127.0303341)",0.481178
1,행당중학교,서울특별시 성동구 왕십리로 189,행당동,37.561700,127.034703,37.559076,127.035869,"(37.559076, 127.035869)","(37.5617004, 127.0347032)","(37.5617004, 127.0347032)",0.308953

In [31]:
# 거리 df 를 만들어준다.
distance = data[['학교명', '주소', '법정동', 'distance']]

In [32]:
distance

                학교명                    주소    법정동  distance
0          서울숭신초등학교     서울특별시 성동구 마장로 161  하왕십리동  0.481178
1             행당중학교    서울특별시 성동구 왕십리로 189    행당동  0.308953
2    한양대학교사범대학부속중학교      서울특별시 성동구 마조로 42    사근동  0.256671
3             옥정중학교     서울특별시 성동구 한림말길 11    옥수동  0.230049
4             성원중학교   서울특별시 성동구 성덕정9가길 13  성수동2가  0.488289
5             성수중학교     서울특별시 성동구 서울숲길 18  성수동1가  0.500910
6             무학중학교     서울특별시 성동구 행당로 120    행당동  1.035611
7             마장중학교  서울특별시 성동구 마장로35나길 31    마장동  0.209178
8             동마중학교   서울특별시 성동구 마조로11길 18    마장동  0.619500
9             광희중학교  서울특별시 성동구 독서당로62길 46    응봉동  0.168591
10            경일중학교     서울특별시 성동구 성수일로 27  성수동1가  0.808645
11            경수중학교   서울특별시 성동구 뚝섬로13길 14  성수동2가  0.200844
12           한양초등학교    서울특별시 성동구 살곶이길 208    사근동  0.950259
13         서울행현초등학교      서울특별시 성동구 행당로 95    행당동  1.035611
14         서울행당초등학교    서울특별시 성동구 고산자로8길 6    행당동  0.139361
15         서울응봉초등학교  서울특별시 성동구 독서당로62길 28    응봉동  0.168591
16         서울용답초등학교     서울특별시 성동구 용답25길 1    용답동  0.348662
17         서울옥정초등학교     서울특별시 성동구 한림말길 43    옥수동  0.230049
18         서울옥수초등학교    서울특별시 성동구 금호로1길 25  금호동4가  0.354109
19         서울송원초등학교    서울특별시 성동구 동일로43길 9    송정동  0.342245
20         서울성수초등학교  서울특별시 성동구 아차산로17길 21  성수동2가  0.733167
21         서울사근초등학교   서울특별시 성동구 사근동11길 16    사근동  0.146024
22         서울무학초등학교   서울특별시 성동구 무학봉15길 21  하왕십리동  0.104859
23         서울마장초등학교  서울특별시 성동구 마장로35나길 31    마장동  0.209178
24         서울동호초등학교   서울특별시 성동구 매봉길 49-35    옥수동  0.427381
25         서울동명초등학교   서울특별시 성동구 마장로29길 29    마장동  0.238662
26         서울금호초등학교     서울특별시 성동구 무수막길 69  금호동2가  0.319570
27         서울금옥초등학교    서울특별시 성동구 독서당로 251  금호동4가  0.275335
28         서울금북초등학교    서울특별시 성동구 행당로1길 13  금호동1가  0.156865
29         서울경일초등학교     서울특별시 성동구 뚝섬로 332  성수동1가  1.848675
30         서울경수초등학교   서울특별시 성동구 뚝섬로13길 22  성수동2가  0.200844
31         서울경동초등학교     서울특별시 성동구 성수일로 34  성수동1가  0.808645
32           금호고등학교     서울특별시 성동구 금호로 118  금호동1가  0.191076
33           도선고등학교     서울특별시 성동구 마장로 156  하왕십리동  0.481178
34           성수고등학교     서울특별시 성동구 서울숲길 18  성수동1가  0.500910
35         서울방송고등학교   서울특별시 성동구 동호로5길 131    옥수동  0.622903
36           덕수고등학교    서울특별시 성동구 왕십리로 199    행당동  0.308953
37  한양대학교사범대학부속고등학교      서울특별시 성동구 마조로 42    사근동  0.256671
38           경일고등학교     서울특별시 성동구 성수일로 27  성수동1가  0.808645
39         성수공업고등학교     서울특별시 성동구 뚝섬로 365  성수동2가  3.028226
40         무학여자고등학교    서울특별시 성동구 고산자로 197    행당동  1.378941

In [33]:
# 동을 기준으로 묶고 그 동에 있는 학교의 거리 평균을 구해준다.
distance_mean = distance.groupby('법정동')['distance'].mean()

In [34]:
distance_mean

법정동
금호동1가    0.173971
금호동2가    0.319570
금호동4가    0.314722
마장동      0.319129
사근동      0.402406
성수동1가    0.879405
성수동2가    0.930274
송정동      0.342245
옥수동      0.377596
용답동      0.348662
응봉동      0.168591
하왕십리동    0.355738
행당동      0.701238
Name: distance, dtype: float64

In [35]:
distance_mean.to_csv('school_distance.csv')